Content-Security-Policy:
	default-src 'self';
	base-uri 'self';
	form-action 'self';
	frame-ancestors 'self';

	script-src 'self' 'strict-dynamic' 'nonce-{nonce}';
	script-src-elem 'self' 'strict-dynamic' 'nonce-{nonce}';
	script-src-attr 'self' 'nonce-{nonce}';

	style-src 'self' 'unsafe-inline';
	style-src-elem 'self' 'unsafe-inline';

	img-src 'self' data:;
	font-src 'self' data:;

	frame-src 'self';
	media-src 'self';
	object-src 'none';

	connect-src 'self';
	worker-src 'self';

	upgrade-insecure-requests;

	report-uri /csp-reports;
	report-to csp-endpoint;