Content-Security-Policy:
	default-src 'self';
	base-uri 'self';
	form-action 'self';
	frame-ancestors 'self';

	script-src 'self' 'nonce-{nonce}' 'strict-dynamic';
	script-src-elem 'self' 'nonce-{nonce}' 'strict-dynamic';
	script-src-attr 'self' 'nonce-{nonce}';

	style-src 'self' 'unsafe-inline';
	style-src-elem 'self' 'unsafe-inline';

	img-src * data:;
	font-src 'self' data: https:;

	frame-src 'self' 
		archive.org *.youtube.com *.youtube-nocookie.com 
		*.dailymotion.com *.bitchute.com odysee.com 
		*.vimeo.com rumble.com;

	media-src 'self' 
		archive.org *.youtube.com *.youtube-nocookie.com 
		dailymotion.com *.bitchute.com odysee.com 
		*.vimeo.com rumble.com;

	object-src 'self' 
		archive.org *.googlevideo.com *.ytimg.com 
		*.youtube.com *.youtube-nocookie.com 
		dailymotion.com *.bitchute.com odysee.com 
		*.vimeo.com rumble.com;

	upgrade-insecure-requests;

	report-uri /csp-reports;
	report-to csp-endpoint;