<?php

if (!defined('IN_WACKO'))
{
	exit;
}

use BadBehaviour\Core\ResultCode;
use BadBehaviour\Core\BadBehaviour;

##########################################################
##	Bad Behaviour										##
##########################################################

$module['tool_badbehaviour'] = [
	'order'	=> 800,
	'cat'	=> 'extension',
	'status'=> !RECOVERY_MODE,
];

##########################################################
function admin_tool_badbehaviour($engine, $module)
{
	if (!empty($engine->db->ext_bad_behaviour))
	{
		// No legacy responses.inc.php to require — Bad Behaviour 3.0 is autoloaded.
	}

	// Replace bb2_get_response() with ResultCode enum
	function bb2_get_response($key)
	{
		try {
			$code = ResultCode::from($key);
			return [
				'response'    => $code->http_status(),
				'explanation' => $code->getMessage() ?? '',
				'log'         => $code->value,
			];
		} catch (\ValueError $e) {
			// Legacy 2.x hex or unknown
			return ['response' => 403, 'explanation' => 'Unknown error', 'log' => $key];
		}
	}

	$action = $_POST['_action'] ?? null;

	// ============================================================
	// READ / WRITE settings (nested shape, matches bb_config.php)
	// ============================================================

	function bb2_read_settings($engine)
	{
		$adapter = new \BadBehaviour\Adapter\WackoWikiAdapter($engine->db);

		return $adapter->get_settings();
	}

	function bb2_write_settings($engine, array $settings): array
	{
		// Strip adapter-only keys (not part of bb_config.php schema)
		unset($settings['adapter'], $settings['log_table']);

		$config_dir = defined('CONFIG_DIR') ? CONFIG_DIR : 'config';

		if (!is_dir($config_dir))
		{
			@mkdir($config_dir, 0755, true);
		}

		if (!is_writable($config_dir))
		{
			return ['success' => false, 'error' => "Config directory not writable: {$config_dir}"];
		}

		// CRITICAL: must match what Configuration::from_file() reads.
		$file = $config_dir . '/bb_config.php';

		$header = "<?php\n"
			. "/**\n"
				. " * Bad Behaviour configuration\n"
					. " * Generated by WackoWiki admin module — " . date('c') . "\n"
						. " * DO NOT EDIT WHILE THE ADMIN UI IS OPEN — changes will be overwritten.\n"
							. " */\n\n"
								. "return " . var_export($settings, true) . ";\n";

								// Atomic write
								$tmp = $file . '.tmp.' . bin2hex(random_bytes(4));
								$bytes = @file_put_contents($tmp, $header, LOCK_EX);

								if ($bytes === false)
								{
									$err = error_get_last();

									return ['success' => false, 'error' => "Failed to write temp: {$tmp} — " . ($err['message'] ?? 'unknown')];
								}

								if (!@rename($tmp, $file))
								{
									@unlink($tmp);
									$err = error_get_last();

									return ['success' => false, 'error' => "Failed to rename → {$file} — " . ($err['message'] ?? 'unknown')];
								}

								@chmod($file, 0644);

								return ['success' => true, 'file' => $file, 'bytes' => $bytes];
	}

	// ============================================================
	// SAVE — called by the bottom dispatcher when _action=bb2_save
	// ============================================================

	function bb2_save_settings($engine): array
	{
		// Update core on/off in main config table
		$config['ext_bad_behaviour'] = (int)($_POST['ext_bad_behaviour'] ?? 0);
		$engine->db->_set($config);

		// Read existing for custom_rules preservation (UI doesn't edit yet,
		// but we round-trip what's in the file)
		$existing = bb2_read_settings($engine);

		// ===== CUSTOM RULES — JSON-per-line =====
		// Each non-empty line is a JSON object: {"type":"ip","value":"1.2.3.4","action":"block","id":"..."}
		$custom_rules	= [];
		$raw_custom		= (string)($_POST['custom_rules'] ?? '');

		foreach (preg_split('/\r\n|\r|\n/', $raw_custom) as $line)
		{
			$line = trim($line);

			if ($line === '')
			{
				continue;
			}

			$decoded = json_decode($line, true);

			if (is_array($decoded) && isset($decoded['type'], $decoded['action']))
			{
				$custom_rules[] = $decoded;
			}
			else
			{
				return [
					'success'  => false,
					'error'    => 'Invalid JSON in custom_rules: ' . htmlspecialchars(substr($line, 0, 80)),
					'payload'  => $_POST,
				];
			}
		}

		// ===== BODY SCAN — one field name per line =====
		$body_scan_skip_fields = array_filter(
			array_map('trim', preg_split('/\r\n|\r|\n/', (string)($_POST['body_scan_skip_fields'] ?? '')))
			);

		$new_settings = [
			// ===== CORE =====
			'logging'                    => !empty($_POST['logging']),
			'verbose'                    => !empty($_POST['verbose']),
			'strict'                     => !empty($_POST['strict']),
			'offsite_forms'              => !empty($_POST['offsite_forms']),

			// ===== BLOCK PAGE =====
			'show_contact_info'          => !empty($_POST['show_contact_info']),
			'show_detailed_block_page'   => !empty($_POST['show_detailed_block_page']),

			// ===== REVERSE PROXY =====
			'reverse_proxy' => [
				'enabled'   => !empty($_POST['reverse_proxy']),
				'header'    => $_POST['reverse_proxy_header'] ?? 'X-Forwarded-For',
				'addresses' => array_filter(array_map('trim', explode("\n", $_POST['reverse_proxy_addresses'] ?? ''))),
			],

			// ===== HTTP:BL =====
			'httpbl' => [
				'key'    => preg_match('/^[a-z]{12}$/', $_POST['httpbl_key'] ?? '') ? $_POST['httpbl_key'] : '',
				'threat' => max(0, min(255, (int)($_POST['httpbl_threat'] ?? 25))),
				'maxage' => max(0, (int)($_POST['httpbl_maxage'] ?? 30)),
			],

			// ===== DNSBL =====
			'dnsbl' => [
				'enabled' => !empty($_POST['dnsbl_enabled']),
				'lists'   => array_filter(array_map('trim', explode("\n", $_POST['dnsbl_lists'] ?? ''))),
			],

			// ===== AI CRAWLERS =====
			'ai_crawlers' => [
				'allowed'          => array_filter(array_map('trim', explode("\n", $_POST['allowed_ai_crawlers'] ?? ''))),
				'block_unverified' => !empty($_POST['block_unverified_ai']),
				'strict'           => !empty($_POST['strict_ai']),
			],

			// ===== BOT CATEGORIES =====
			'bot_categories' => [
				'blocked' => $existing['bot_categories']['blocked'] ?? ['malicious'],
			],

			// ===== RATE LIMITS =====
			'rate_limits' => [
				'enabled'    => !empty($_POST['rate_limit_enabled']),
				'global'     => [
					'requests' => max(1, (int)($_POST['rate_global_requests'] ?? 1000)),
					'window'   => max(1, (int)($_POST['rate_global_window']   ?? 3600)),
				],
				'per_minute' => [
					'requests' => max(1, (int)($_POST['rate_per_minute_requests'] ?? 60)),
					'window'   => max(1, (int)($_POST['rate_per_minute_window']   ?? 60)),
				],
				'post'       => [
					'requests' => max(1, (int)($_POST['rate_post_requests'] ?? 30)),
					'window'   => max(1, (int)($_POST['rate_post_window']   ?? 3600)),
				],
				'login'      => [
					'requests' => max(1, (int)($_POST['rate_login_requests'] ?? 10)),
					'window'   => max(1, (int)($_POST['rate_login_window']   ?? 900)),
				],
			],

			// ===== CHALLENGE =====
			'challenge' => [
				'enabled'             => !empty($_POST['challenge_enabled']),
				'provider'            => in_array($_POST['challenge_provider'] ?? '', ['builtin', 'hcaptcha', 'recaptcha', 'turnstile'], true)
					? $_POST['challenge_provider']
					: 'builtin',
				'site_key'            => trim($_POST['challenge_site_key'] ?? ''),
				'secret_key'          => trim($_POST['challenge_secret_key'] ?? ''),
				'recaptcha_min_score' => max(0.0, min(1.0, (float)($_POST['recaptcha_min_score'] ?? 0.5))),
			],

			// ===== PERFORMANCE =====
			'performance' => [
				'skip_extensions' => array_filter(array_map('trim', explode("\n", $_POST['skip_static_extensions'] ?? ''))),
				'skip_paths'      => array_filter(array_map('trim', explode("\n", $_POST['skip_static_paths'] ?? ''))),
			],

			// ===== GEOIP =====
			'geoip' => [
				'enabled'           => !empty($_POST['geoip_enabled']),
				'database_path'     => trim($_POST['geoip_database_path'] ?? ''),
				'blocked_countries' => array_filter(array_map('trim', explode("\n", $_POST['blocked_countries'] ?? ''))),
				'blocked_asns'      => array_filter(array_map('trim', explode("\n", $_POST['blocked_asns'] ?? ''))),
			],

			// ===== FINGERPRINTS =====
			'fingerprints' => [
				'bad_ja3'           => array_filter(array_map('trim', explode("\n", $_POST['bad_ja3_fingerprints'] ?? ''))),
				'bad_h2'            => array_filter(array_map('trim', explode("\n", $_POST['bad_h2_fingerprints'] ?? ''))),
				'bot_header_orders' => array_filter(array_map('trim', explode("\n", $_POST['bot_header_orders'] ?? ''))),
				'expected_ja3'      => array_filter(array_map('trim', explode("\n", $_POST['expected_ja3'] ?? ''))),
			],

			// ===== BODY SCAN =====
			'body_scan_skip_fields' => $body_scan_skip_fields,

			// ===== CUSTOM RULES =====
			'custom_rules' => $custom_rules,

			// ===== 3.0 FEATURES =====
			'enable_fingerprinting'          => !empty($_POST['enable_fingerprinting']),
			'inspect_json_body'              => !empty($_POST['inspect_json_body']),
			'inspect_multipart_body'         => !empty($_POST['inspect_multipart_body']),
			'enable_behavioral_analysis'     => !empty($_POST['enable_behavioral_analysis']),
			'enable_ai_crawler_control'      => !empty($_POST['enable_ai_crawler_control']),
			'enable_client_hints_validation' => !empty($_POST['enable_client_hints_validation']),
			'enable_agentic_detection'       => !empty($_POST['enable_agentic_detection']),
			'enable_dynamic_ip_ranges'       => !empty($_POST['enable_dynamic_ip_ranges']),
		];

		$write = bb2_write_settings($engine, $new_settings);

		if (!$write['success'])
		{
			return [
				'success' => false,
				'error'   => $write['error'],
				'payload' => $new_settings,
			];
		}

		return ['success' => true, 'file' => $write['file']];
	}

	// ============================================================
	// WHITELIST (INI file)
	// ============================================================

	function bb2_read_whitelist($engine)
	{
		$adapter = new \BadBehaviour\Adapter\WackoWikiAdapter($engine->db);
		return $adapter->get_whitelist();
	}

	// ============================================================
	// HTTP:BL lookup
	// ============================================================

	/**
	 * Lookup an IP in Project Honey Pot's http:BL.
	 * Returns a human-readable description string, or empty string on miss.
	 *
	 * Cache: stored in $engine->sess->httpbl[ip] = "127.x.x.x" for 24h.
	 */
	function bb2_httpbl_lookup($engine, $ip): string
	{
		$settings	= bb2_read_settings($engine);
		$key		= $settings['httpbl']['key'] ?? '';

		if (!preg_match('/^[a-z]{12}$/', $key))
		{
			return '';
		}

		// Validate IP (IPv4 only — http:BL doesn't support IPv6)
		if (!filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4))
		{
			return '';
		}

		$cache = $engine->sess->httpbl ?? [];

		// Cached?
		if (isset($cache[$ip]) && $cache[$ip] !== '')
		{
			$r = $cache[$ip];
		}
		else
		{
			// Reverse octets for http:BL query
			$find	= implode('.', array_reverse(explode('.', $ip)));
			$query	= "{$key}.{$find}.dnsbl.httpbl.org.";
			$resp	= @gethostbynamel($query);

			if (empty($resp))
			{
				$cache[$ip] = '';
				$engine->sess->httpbl = $cache;

				return '';
			}

			$r = $resp[0];
			$cache[$ip] = $r;
			$engine->sess->httpbl = $cache;
		}

		// http:BL response: 127.<activity>.<threat>.<type>
		$parts = explode('.', $r);

		if (count($parts) !== 4 || $parts[0] !== '127')
		{
			return '';
		}

		$activity	= (int)$parts[1];
		$threat		= (int)$parts[2];
		$type		= (int)$parts[3];

		$out = [];

		// Type 0 = known search engine (whitelist candidate)
		if ($type === 0)
		{
			$out[] = 'Search engine (whitelist candidate)';
		}
		// Type bit flags
		if ($type & 1) $out[] = 'Suspicious';
		if ($type & 2) $out[] = 'Harvester';
		if ($type & 4) $out[] = 'Comment spammer';
		if ($type & 7) $out[] = "Threat level {$threat}";
		if ($activity > 0) $out[] = "Age {$activity} days";

		return implode('<br>', $out);
	}

	// ============================================================
	// STATS / SUMMARY / MANAGE / WHITELIST
	// ============================================================

	function bb2_insert_stats($engine)
	{
		$result = $engine->db->load_single(
			"SELECT COUNT(log_id) AS n FROM " . $engine->prefix . 'bad_behaviour ' .
			" WHERE `status_code` NOT LIKE '00000000'"
		);

		return $result['n'] ?: '';
	}

	function bb2_summary($engine)
	{
		echo $engine->form_open('bb2_manage', ['form_more' => 'setting=bb2_manage']);
		?>

		<div class="alignleft">
		<?php echo Ut::perc_replace($engine->_t('BbStats'), '<strong>' . bb2_insert_stats($engine) . '</strong>');?>
		</div>
		<?php
		$arguments = ['status_code', 'request_method', 'request_uri'];

		foreach ($arguments as $argument)
		{
			if ($argument == 'request_uri')
			{
				$additional_fields = 'MAX(request_uri_hash) as request_uri_hash, ';
			}
			else
			{
				$additional_fields = '';
			}

			$binary		= $engine->db->binary();
			$results	= $engine->db->load_all(
				'SELECT ' .
					'CAST(' . $argument . ' AS ' . $binary . ') AS group_type, ' .
					$additional_fields .
					' COUNT(' . $argument . ') AS n ' .
				'FROM ' . $engine->prefix . 'bad_behaviour ' .
				'GROUP BY CAST(' . $argument . ' AS ' . $binary . ') ' .
				'ORDER BY n DESC ' .
				'LIMIT 10', true);
		?>
		<table class="bb-summary formation lined">
			<colgroup>
				<col span="1">
				<col span="1">
			</colgroup>
			<thead>
				<tr>
					<th scope="col"><?php echo $engine->_t('BbHits');?></th>
					<th scope="col"><?php echo $argument; ?></th>
				</tr>
			</thead>
			<tbody>
		<?php
			if ($results)
			{
				foreach ($results as $result)
				{
					echo '<tr>' . "\n";
					echo '<td class="label">' . $result['n'] . '</td>' . "\n";

					if ($argument == 'status_code')
					{
						$status_code = bb2_get_response($result['group_type']);
						$link = '<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'status_code' => $result['group_type']]) . '" title="' . '[' . $status_code['response'] . '] ' . $status_code['explanation'] . '">' . $status_code['log'] . '</a>';
					}
					else if ($argument == 'request_uri')
					{
						$link = '<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', $argument => $result['request_uri_hash']]) . '">' . $result['group_type'] . '</a>';
					}
					else
					{
						$link = '<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', $argument => $result['group_type']]) . '">' . $result['group_type'] . '</a>';
					}

					echo '<td>' . $link . '</td>' . "\n";
					echo '</tr>' . "\n";
				}
			}
	?>
		</tbody>
	</table>
	<?php
		}
	}

	function bb2_manage($engine)
	{
		$bb_table		= $engine->prefix . 'bad_behaviour';
		$settings		= bb2_read_settings($engine);

		$where			= '';

		$g_key				= ($_GET['status_code']		?? '');
		$g_blocked			= ($_GET['blocked']			?? '');
		$g_permitted		= ($_GET['permitted']		?? '');
		$g_ip				= ($_GET['ip']				?? '');
		$g_user_agent		= ($_GET['user_agent']		?? '');
		$g_request_method	= ($_GET['request_method']	?? '');
		$g_request_uri		= ($_GET['request_uri']		?? '');

		$limit = 100;

		if (!empty($g_key))					$where .= 'AND `status_code`		= ' . $engine->db->q($g_key) . ' ';
		if (!empty($g_blocked))				$where .= "AND `status_code` 		!= '00000000' ";
		else if (!empty($g_permitted))		$where .= "AND `status_code`		= '00000000' ";

		if (!empty($g_ip))					$where .= 'AND `ip` 				= ' . $engine->db->q($g_ip) . ' ';
		if (!empty($g_user_agent))			$where .= 'AND `user_agent_hash`	= ' . $engine->db->q($g_user_agent) . ' ';
		if (!empty($g_request_method))		$where .= 'AND `request_method`		= ' . $engine->db->q($g_request_method) . ' ';
		if (!empty($g_request_uri))			$where .= 'AND `request_uri_hash`	= ' . $engine->db->q($g_request_uri) . ' ';

		$count = $engine->db->load_single(
			'SELECT COUNT(log_id) AS n ' .
			'FROM ' . $engine->prefix . 'bad_behaviour l ' .
			'WHERE 1=1 ' . ( $where ?: '' ));

		$pagination			= $engine->pagination($count['n'], $limit, 'p', ['mode' => 'tool_badbehaviour', 'setting' => 'bb2_manage']
								+ (!empty($g_blocked)			? ['blocked'		=> Ut::html($g_blocked)] : [])
								+ (!empty($g_permitted)			? ['permitted'		=> Ut::html($g_permitted)] : [])
								+ (!empty($g_key)				? ['status_code'	=> Ut::html($g_key)] : [])
								+ (!empty($g_ip)				? ['ip'				=> Ut::html($g_ip)] : [])
								+ (!empty($g_request_method)	? ['request_method'	=> Ut::html($g_request_method)] : [])
								+ (!empty($g_request_uri)		? ['request_uri'	=> Ut::html($g_request_uri)] : [])
								+ (!empty($g_user_agent)		? ['user_agent'		=> Ut::html($g_user_agent)] : []), '', 'admin.php');

		$totalcount		= $engine->db->load_single(
			'SELECT COUNT(log_id) AS n ' .
			'FROM ' . $engine->prefix . 'bad_behaviour l ');

		$results		= $engine->db->load_all(
			'SELECT log_id, ip, host, date, request_method, request_uri, server_protocol, http_headers, user_agent, user_agent_hash, request_entity, status_code ' .
			'FROM `' . $bb_table . '` ' .
			'WHERE 1=1 ' .
			$where .
			'ORDER BY `log_id` DESC ' .
			$pagination['limit']);

		echo $engine->form_open('bb2_manage');
		?>

		<div class="alignleft">
		<?php
		echo Ut::perc_replace($engine->_t('BbRecordsFiltered'), '<strong>' . $count['n'] . '</strong>', '<strong>' . $totalcount['n'] . '</strong>') . ':<br>';
		echo $engine->_t('BbShow') . ' ';

		if ($count['n'] < $totalcount['n'])
		{
			$link = '[<a href="' .	$engine->href('', '', ['setting' => 'bb2_manage']) . '">X</a>]';

			if (!empty($g_key))				echo '<strong>' . $engine->_t('BbStatus')		. '</strong> ' . $link . ' ';
			if (!empty($g_blocked))			echo '<strong>' . $engine->_t('BbBlocked')		. '</strong> ' . $link . ' ';
			if (!empty($g_permitted))		echo '<strong>' . $engine->_t('BbPermitted')	. '</strong> ' . $link . ' ';
			if (!empty($g_ip))				echo '<strong>' . $engine->_t('BbIp')			. '</strong> ' . $link . ' ';
			if (!empty($g_user_agent))		echo '<strong>' . $engine->_t('BbUserAgent')	. '</strong> ' . $link . ' ';
			if (!empty($g_request_method))	echo '<strong>' . $engine->_t('BbGetPost')		. '</strong> ' . $link . ' ';
			if (!empty($g_request_uri))		echo '<strong>' . $engine->_t('BbUri')			. '</strong> ' . $link . ' ';
		}

		if (!isset($_GET['status_code']))
		{
			if (!isset($_GET['blocked']))
			{
				echo '<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'blocked' => 'true']) . '">' . $engine->_t('BbBlocked') . '</a> ';
			}

			if (!isset($_GET['permitted']))
			{
				echo ' <a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'permitted' => 'true']) . '">' . $engine->_t('BbPermitted') . '</a>';
			}
		}
		?>
		</div>

		<?php
		$engine->print_pagination($pagination);
		?>
		<table class="formation hl-line bb-log">
			<thead>
				<tr>
					<th scope="col" class="check-column"></th>
					<th scope="col"><?php echo $engine->_t('BbIpDateStatus');?></th>
					<th scope="col"><?php echo $engine->_t('BbHeaders');?></th>
					<th scope="col"><?php echo $engine->_t('BbEntity');?></th>
				</tr>
			</thead>
			<tbody>
		<?php
		if ($results)
		{
			foreach ($results as $result)
			{
				$status_code = bb2_get_response($result['status_code']);

				echo '<tr id="request-' . $result['log_id'] . '">' . "\n";
				echo '<td class="check-column label">' .
						'<input type="checkbox" name="submit[]" value="' . $result['log_id'] . '">' .
					'</td>' . "\n";

				$httpbl	= bb2_httpbl_lookup($engine, $result['ip']);

				if (empty($result['host']))
				{
					$host = @gethostbyaddr($result['ip']);
					$engine->db->sql_query(
						'UPDATE ' . $engine->prefix . 'bad_behaviour SET ' .
							'host		= ' . $engine->db->q($host) . ' ' .
						'WHERE log_id	= ' . (int) $result['log_id'] . ' ' .
						$engine->db->limit());
				}

				$host = $result['host'];

				if (!strcmp($host, $result['ip']))
				{
					$host = '';
				}
				else
				{
					$host .= "<br>\n";
				}

				$time_tz = $engine->sql2precisetime($result['date']);

				echo '<td>' .
						'<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'ip' => $result['ip']]) . '">' . $result['ip'] . '</a><br>' .
						$host . '<br>' . "\n" .
						$time_tz . '<br><br>' .
						'<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'status_code' => $result['status_code']]) . '" title="' .'[' . $status_code['response'] . '] ' . $status_code['explanation']. '">' . $status_code['log'] . '</a>' . "\n";

				if ($httpbl)
				{
					echo "<br><br><a href=\"https://www.projecthoneypot.org/ip_{$result['ip']}\">http:BL</a>:<br>$httpbl\n";
				}

				echo '</td>' . "\n";

				$headers = str_replace("\n", "<br>\n", Ut::html($result['http_headers']));

				if (@str_contains($headers, $result['user_agent']))
				{
					$headers = substr_replace($headers, '<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'user_agent' => rawurlencode($result['user_agent_hash'])]) . '">' . $result['user_agent'] . '</a>', strpos($headers, $result['user_agent']), strlen($result['user_agent']));
				}

				if (@str_contains($headers, $result['request_method']))
				{
					$headers = substr_replace($headers, '<a href="' . $engine->href('', '', ['setting' => 'bb2_manage', 'request_method' => rawurlencode($result['request_method'])]) . '">' . $result['request_method'] . '</a>', strpos($headers, $result['request_method']), strlen($result['request_method']));
				}

				echo '<td>' . $headers . '</td>' . "\n";
				echo '<td>' . str_replace("\n", "<br>\n", Ut::html($result['request_entity'])) . '</td>' . "\n";
				echo '</tr>' . "\n";
			}
		}
	?>
		</tbody>
	</table>

	<?php
		$engine->print_pagination($pagination);

		echo $engine->form_close();
	}

	function bb2_whitelist($engine)
	{
		$whitelists = bb2_read_whitelist($engine);

		if (empty($whitelists))
		{
			$whitelists					= [];
			$whitelists['ip']			= [];
			$whitelists['url']			= [];
			$whitelists['useragent']	= [];
		}

		if ($_POST)
		{
			if ($_POST['ip'])
			{
				$whitelists['ip'] = array_filter(preg_split('/\s+/m', $_POST['ip']));
			}
			else
			{
				$whitelists['ip'] = [];
			}

			if ($_POST['url'])
			{
				$whitelists['url'] = array_filter(preg_split('/\s+/m', $_POST['url']));
			}
			else
			{
				$whitelists['url'] = [];
			}

			if ($_POST['useragent'])
			{
				$whitelists['useragent'] = array_filter(preg_split("/[\r\n]+/m", $_POST['useragent']));
			}
			else
			{
				$whitelists['useragent'] = [];
			}

		?>
		<div id="message" class="updated fade"><p><strong><?php echo $engine->_t('BbOptionsSaved');?></strong></p></div>
		<?php
		}

		echo $engine->form_open('bb2_whitelist', ['form_more' => 'setting=bb2_whitelist']);
		?>
		<p><?php echo $engine->_t('BbWhitelistHint');?></p>

		<table class="setting formation">
			<colgroup>
				<col span="1">
				<col span="1">
			</colgroup>
			<tr>
				<th colspan="2">
					<br>
					<?php echo $engine->_t('BbWhitelist');?>
				</th>
			</tr>
			<tr class="hl-setting">
				<td class="label">
					<label for="whitelists_ip"><strong><?php echo $engine->_t('BbIpAddress');?>:</strong><br>
					<small><?php echo $engine->_t('BbIpAddressInfo');?></small></label>
				</td>
				<td>
					<textarea cols="30" rows="6" id="whitelists_ip" name="ip"><?php echo implode("\n", $whitelists['ip']); ?></textarea>
				</td>
			</tr>
			<tr class="lined">
				<td colspan="2"></td></tr>
			<tr class="hl-setting">
				<td class="label">
					<label for="whitelists_url"><strong><?php echo $engine->_t('BbUrl');?>:</strong><br>
					<small><?php echo $engine->_t('BbUrlInfo');?></small></label>
				</td>
				<td>
					<textarea cols="50" rows="6" id="whitelists_url" name="url"><?php echo implode("\n", $whitelists['url']); ?></textarea>
				</td>
			</tr>
			<tr class="lined">
				<td colspan="2"></td></tr>
			<tr class="hl-setting">
				<td class="label">
					<label for="whitelists_useragent"><strong><?php echo $engine->_t('BbUserAgent');?>:</strong><br>
					<small><?php echo $engine->_t('BbUserAgentInfo');?></small></label>
				</td>
				<td>
					<textarea cols="50" rows="6" id="whitelists_useragent" name="useragent"><?php echo implode("\n", $whitelists['useragent']); ?></textarea>
				</td>
			</tr>
		</table>
		<br>
		<div class="center"><button type="submit" class="button" name="submit"><?php echo $engine->_t('UpdateButton');?></button></div>

	<?php
		echo $engine->form_close();
	}

	// ============================================================
	// OPTIONS — view only (renders form)
	// Saving happens in bb2_save_settings() called by the bottom dispatcher
	// ============================================================

	function bb2_options($engine, array $settings = null)
	{
		if ($settings === null)
		{
			$settings = bb2_read_settings($engine);
		}

		// Show stale-error message if present (from failed save)
		if (!empty($_GET['bb_save_error']))
		{
			echo '<div id="message" class="error fade"><p><strong>' .
				$engine->_t('BbSettingsSaveFailed') . ':</strong> ' .
				htmlspecialchars(base64_decode($_GET['bb_save_error'])) . '</p></div>';
		}

	?>
	<div class="wrap">
<?php
	echo $engine->form_open('bb2_options', ['form_more' => 'setting=bb2_options']);
?>
	<table class="setting formation">
		<colgroup>
			<col span="1">
			<col span="1">
		</colgroup>

		<!-- ENABLE/DISABLE -->
		<tr class="lined"><td colspan="2"></td></tr>
		<tr class="hl-setting">
			<td class="label"><strong><?php echo $engine->_t('BbEnable');?></strong><br>
				<small><?php echo Ut::perc_replace($engine->_t('BbEnableInfo'), '<code>bb_config.php</code>');?></small></td>
			<td>
				<input type="radio" id="enable_bad-behaviour_on" name="ext_bad_behaviour" value="1"<?php echo ($engine->db->ext_bad_behaviour ? ' checked' : '');?>>
				<label for="enable_bad-behaviour_on"><?php echo $engine->_t('On');?></label>
				<input type="radio" id="enable_bad-behaviour_off" name="ext_bad_behaviour" value="0"<?php echo (!$engine->db->ext_bad_behaviour ? ' checked' : '');?>>
				<label for="enable_bad-behaviour_off"><?php echo $engine->_t('Off');?></label>
			</td>
		</tr>

		<!-- LOGGING -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbLogRequest');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="logging_verbose"><?php echo $engine->_t('BbLogVerbose');?></label></td>
			<td><input type="checkbox" id="logging_verbose" name="verbose" value="1"<?php echo (!empty($settings['verbose']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="logging_normal"><?php echo $engine->_t('BbLogNormal');?></label></td>
			<td><input type="checkbox" id="logging_normal" name="logging" value="1"<?php echo (!empty($settings['logging']) ? ' checked' : '');?>></td>
		</tr>

		<!-- SECURITY -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbSecurity');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="strict_checking"><strong><?php echo $engine->_t('BbStrict');?></strong><br><?php echo $engine->_t('BbStrictInfo');?></label></td>
			<td><input type="checkbox" id="strict_checking" name="strict" value="1"<?php echo (!empty($settings['strict']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="lined"><td colspan="2"></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="offsite_forms"><strong><?php echo $engine->_t('BbOffsiteForms');?></strong><br><?php echo $engine->_t('BbOffsiteFormsInfo');?></label></td>
			<td><input type="checkbox" id="offsite_forms" name="offsite_forms" value="1"<?php echo (!empty($settings['offsite_forms']) ? ' checked' : '');?>></td>
		</tr>

		<!-- BLOCK PAGE (NEW in 3.0) -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbBlockPage');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="show_detailed_block_page"><strong><?php echo $engine->_t('BbShowDetailedBlockPage');?></strong><br><?php echo $engine->_t('BbShowDetailedBlockPageInfo');?></label></td>
			<td><input type="checkbox" id="show_detailed_block_page" name="show_detailed_block_page" value="1"<?php echo (!empty($settings['show_detailed_block_page']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="show_contact_info"><strong><?php echo $engine->_t('BbShowContactInfo');?></strong><br><?php echo $engine->_t('BbShowContactInfoInfo');?></label></td>
			<td><input type="checkbox" id="show_contact_info" name="show_contact_info" value="1"<?php echo (!empty($settings['show_contact_info']) ? ' checked' : '');?>></td>
		</tr>

		<!-- BEHAVIORAL ANALYSIS -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbBehavioral');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="enable_behavioral"><strong><?php echo $engine->_t('BbEnableBehavioral');?></strong><br><?php echo $engine->_t('BbEnableBehavioralInfo');?></label></td>
			<td><input type="checkbox" id="enable_behavioral" name="enable_behavioral_analysis" value="1"<?php echo (!empty($settings['enable_behavioral_analysis']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="enable_fingerprinting"><strong><?php echo $engine->_t('BbEnableFingerprinting');?></strong><br><?php echo $engine->_t('BbEnableFingerprintingInfo');?></label></td>
			<td><input type="checkbox" id="enable_fingerprinting" name="enable_fingerprinting" value="1"<?php echo (!empty($settings['enable_fingerprinting']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="inspect_json"><strong><?php echo $engine->_t('BbInspectJson');?></strong><br><?php echo $engine->_t('BbInspectJsonInfo');?></label></td>
			<td><input type="checkbox" id="inspect_json" name="inspect_json_body" value="1"<?php echo (!empty($settings['inspect_json_body']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="inspect_multipart"><strong><?php echo $engine->_t('BbInspectMultipart');?></strong><br><?php echo $engine->_t('BbInspectMultipartInfo');?></label></td>
			<td><input type="checkbox" id="inspect_multipart" name="inspect_multipart_body" value="1"<?php echo (!empty($settings['inspect_multipart_body']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="enable_ai_crawler_control"><strong><?php echo $engine->_t('BbEnableAiCrawlerControl');?></strong><br><?php echo $engine->_t('BbEnableAiCrawlerControlInfo');?></label></td>
			<td><input type="checkbox" id="enable_ai_crawler_control" name="enable_ai_crawler_control" value="1"<?php echo (!empty($settings['enable_ai_crawler_control']) ? ' checked' : '');?>></td>
		</tr>

		<!-- 3.0 FEATURES -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbModernFeatures');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="enable_client_hints"><strong><?php echo $engine->_t('BbEnableClientHints');?></strong><br><?php echo $engine->_t('BbEnableClientHintsInfo');?></label></td>
			<td><input type="checkbox" id="enable_client_hints" name="enable_client_hints_validation" value="1"<?php echo (!empty($settings['enable_client_hints_validation']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="enable_agentic"><strong><?php echo $engine->_t('BbEnableAgentic');?></strong><br><?php echo $engine->_t('BbEnableAgenticInfo');?></label></td>
			<td><input type="checkbox" id="enable_agentic" name="enable_agentic_detection" value="1"<?php echo (!empty($settings['enable_agentic_detection']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="enable_dynamic_ip"><strong><?php echo $engine->_t('BbEnableDynamicIp');?></strong><br><?php echo $engine->_t('BbEnableDynamicIpInfo');?></label></td>
			<td><input type="checkbox" id="enable_dynamic_ip" name="enable_dynamic_ip_ranges" value="1"<?php echo (!empty($settings['enable_dynamic_ip_ranges']) ? ' checked' : '');?>></td>
		</tr>

		<!-- AI CRAWLERS -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbAiCrawlers');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="block_unverified_ai"><strong><?php echo $engine->_t('BbBlockUnverifiedAi');?></strong><br><?php echo $engine->_t('BbBlockUnverifiedAiInfo');?></label></td>
			<td><input type="checkbox" id="block_unverified_ai" name="block_unverified_ai" value="1"<?php echo (!empty($settings['ai_crawlers']['block_unverified']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="strict_ai"><strong><?php echo $engine->_t('BbStrictAi');?></strong><br><?php echo $engine->_t('BbStrictAiInfo');?></label></td>
			<td><input type="checkbox" id="strict_ai" name="strict_ai" value="1"<?php echo (!empty($settings['ai_crawlers']['strict']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="allowed_ai_crawlers"><strong><?php echo $engine->_t('BbAllowedAiCrawlers');?></strong><br><?php echo $engine->_t('BbAllowedAiCrawlersInfo');?></label></td>
			<td>
				<textarea cols="50" rows="4" id="allowed_ai_crawlers" name="allowed_ai_crawlers"><?php echo htmlspecialchars(implode("\n", $settings['ai_crawlers']['allowed'] ?? [])); ?></textarea>
			</td>
		</tr>

		<!-- HTTP:BL -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbHttpbl');?></th></tr>
		<tr class="hl-setting"><td colspan="2"><p><?php echo Ut::perc_replace($engine->_t('BbHttpblInfo'), '<a href="https://www.projecthoneypot.org/httpbl_configure.php?rf=24694" rel="noreferrer">http:BL Access Key</a>');?><br></p></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="httpbl_key"><?php echo $engine->_t('BbHttpblKey');?></label></td>
			<td><input type="text" size="12" maxlength="12" id="httpbl_key" name="httpbl_key" value="<?php echo htmlspecialchars($settings['httpbl']['key'] ?? ''); ?>"></td>
		</tr>
		<tr class="lined"><td colspan="2"></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="httpbl_threat"><?php echo $engine->_t('BbHttpblThreat');?></label></td>
			<td><input type="text" size="3" maxlength="3" id="httpbl_threat" name="httpbl_threat" value="<?php echo intval($settings['httpbl']['threat'] ?? 25); ?>"></td>
		</tr>
		<tr class="lined"><td colspan="2"></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="httpbl_maxage"><?php echo $engine->_t('BbHttpblMaxage');?></label></td>
			<td><input type="text" size="3" maxlength="3" id="httpbl_maxage" name="httpbl_maxage" value="<?php echo intval($settings['httpbl']['maxage'] ?? 30); ?>"></td>
		</tr>

		<!-- DNSBL -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbDnsbl');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="dnsbl_enabled"><strong><?php echo $engine->_t('BbDnsblEnabled');?></strong></label></td>
			<td><input type="checkbox" id="dnsbl_enabled" name="dnsbl_enabled" value="1"<?php echo (!empty($settings['dnsbl']['enabled']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="dnsbl_lists"><strong><?php echo $engine->_t('BbDnsblLists');?></strong><br><?php echo $engine->_t('BbDnsblListsInfo');?></label></td>
			<td><textarea cols="50" rows="4" id="dnsbl_lists" name="dnsbl_lists"><?php echo htmlspecialchars(implode("\n", $settings['dnsbl']['lists'] ?? [])); ?></textarea></td>
		</tr>

		<!-- RATE LIMITS -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbRateLimits');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_limit_enabled"><strong><?php echo $engine->_t('BbRateLimitEnabled');?></strong></label></td>
			<td><input type="checkbox" id="rate_limit_enabled" name="rate_limit_enabled" value="1"<?php echo (!empty($settings['rate_limits']['enabled']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_global_requests"><?php echo $engine->_t('BbRateGlobalRequests');?></label></td>
			<td><input type="text" size="6" id="rate_global_requests" name="rate_global_requests" value="<?php echo intval($settings['rate_limits']['global']['requests'] ?? 1000); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_global_window"><?php echo $engine->_t('BbRateGlobalWindow');?></label></td>
			<td><input type="text" size="6" id="rate_global_window" name="rate_global_window" value="<?php echo intval($settings['rate_limits']['global']['window'] ?? 3600); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_per_minute_requests"><?php echo $engine->_t('BbRatePerMinuteRequests');?></label></td>
			<td><input type="text" size="6" id="rate_per_minute_requests" name="rate_per_minute_requests" value="<?php echo intval($settings['rate_limits']['per_minute']['requests'] ?? 60); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_per_minute_window"><?php echo $engine->_t('BbRatePerMinuteWindow');?></label></td>
			<td><input type="text" size="6" id="rate_per_minute_window" name="rate_per_minute_window" value="<?php echo intval($settings['rate_limits']['per_minute']['window'] ?? 60); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_post_requests"><?php echo $engine->_t('BbRatePostRequests');?></label></td>
			<td><input type="text" size="6" id="rate_post_requests" name="rate_post_requests" value="<?php echo intval($settings['rate_limits']['post']['requests'] ?? 30); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_post_window"><?php echo $engine->_t('BbRatePostWindow');?></label></td>
			<td><input type="text" size="6" id="rate_post_window" name="rate_post_window" value="<?php echo intval($settings['rate_limits']['post']['window'] ?? 3600); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_login_requests"><?php echo $engine->_t('BbRateLoginRequests');?></label></td>
			<td><input type="text" size="6" id="rate_login_requests" name="rate_login_requests" value="<?php echo intval($settings['rate_limits']['login']['requests'] ?? 10); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="rate_login_window"><?php echo $engine->_t('BbRateLoginWindow');?></label></td>
			<td><input type="text" size="6" id="rate_login_window" name="rate_login_window" value="<?php echo intval($settings['rate_limits']['login']['window'] ?? 900); ?>"></td>
		</tr>

		<!-- CHALLENGE -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbChallenge');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="challenge_enabled"><strong><?php echo $engine->_t('BbChallengeEnabled');?></strong></label></td>
			<td><input type="checkbox" id="challenge_enabled" name="challenge_enabled" value="1"<?php echo (!empty($settings['challenge']['enabled']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="challenge_provider"><?php echo $engine->_t('BbChallengeProvider');?></label></td>
			<td>
				<select id="challenge_provider" name="challenge_provider">
					<option value="builtin"<?php echo (($settings['challenge']['provider'] ?? 'builtin') === 'builtin' ? ' selected' : '');?>>Builtin (PoW)</option>
					<option value="hcaptcha"<?php echo (($settings['challenge']['provider'] ?? '') === 'hcaptcha' ? ' selected' : '');?>>hCaptcha</option>
					<option value="recaptcha"<?php echo (($settings['challenge']['provider'] ?? '') === 'recaptcha' ? ' selected' : '');?>>reCAPTCHA v3</option>
					<option value="turnstile"<?php echo (($settings['challenge']['provider'] ?? '') === 'turnstile' ? ' selected' : '');?>>Cloudflare Turnstile</option>
				</select>
			</td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="challenge_site_key"><?php echo $engine->_t('BbChallengeSiteKey');?></label></td>
			<td><input type="text" size="40" id="challenge_site_key" name="challenge_site_key" value="<?php echo htmlspecialchars($settings['challenge']['site_key'] ?? ''); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="challenge_secret_key"><?php echo $engine->_t('BbChallengeSecretKey');?></label></td>
			<td><input type="text" size="40" id="challenge_secret_key" name="challenge_secret_key" value="<?php echo htmlspecialchars($settings['challenge']['secret_key'] ?? ''); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="recaptcha_min_score"><?php echo $engine->_t('BbRecaptchaMinScore');?></label></td>
			<td><input type="text" size="4" step="0.1" id="recaptcha_min_score" name="recaptcha_min_score" value="<?php echo htmlspecialchars($settings['challenge']['recaptcha_min_score'] ?? 0.5); ?>"></td>
		</tr>

		<!-- PERFORMANCE -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbPerformance');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="skip_static_extensions"><strong><?php echo $engine->_t('BbSkipExtensions');?></strong></label></td>
			<td><textarea cols="50" rows="3" id="skip_static_extensions" name="skip_static_extensions"><?php echo htmlspecialchars(implode("\n", $settings['performance']['skip_extensions'] ?? [])); ?></textarea></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="skip_static_paths"><strong><?php echo $engine->_t('BbSkipPaths');?></strong></label></td>
			<td><textarea cols="50" rows="3" id="skip_static_paths" name="skip_static_paths"><?php echo htmlspecialchars(implode("\n", $settings['performance']['skip_paths'] ?? [])); ?></textarea></td>
		</tr>

		<!-- GEOIP -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbGeoip');?></th></tr>
		<tr class="hl-setting">
			<td class="label"><label for="geoip_enabled"><strong><?php echo $engine->_t('BbGeoipEnabled');?></strong></label></td>
			<td><input type="checkbox" id="geoip_enabled" name="geoip_enabled" value="1"<?php echo (!empty($settings['geoip']['enabled']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="geoip_database_path"><?php echo $engine->_t('BbGeoipDbPath');?></label></td>
			<td><input type="text" size="60" id="geoip_database_path" name="geoip_database_path" value="<?php echo htmlspecialchars($settings['geoip']['database_path'] ?? ''); ?>"></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="blocked_countries"><?php echo $engine->_t('BbBlockedCountries');?></label></td>
			<td><textarea cols="30" rows="3" id="blocked_countries" name="blocked_countries"><?php echo htmlspecialchars(implode("\n", $settings['geoip']['blocked_countries'] ?? [])); ?></textarea></td>
		</tr>
		<tr class="hl-setting">
			<td class="label"><label for="blocked_asns"><?php echo $engine->_t('BbBlockedAsns');?></label></td>
			<td><textarea cols="30" rows="3" id="blocked_asns" name="blocked_asns"><?php echo htmlspecialchars(implode("\n", $settings['geoip']['blocked_asns'] ?? [])); ?></textarea></td>
		</tr>

		<!-- CUSTOM RULES (NEW in 3.0) -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbCustomRules');?></th></tr>
		<tr class="hl-setting">
			<td class="label">
				<label for="custom_rules"><strong><?php echo $engine->_t('BbCustomRulesLabel');?></strong><br>
				<small><?php echo $engine->_t('BbCustomRulesInfo');?></small></label>
			</td>
			<td>
				<textarea cols="60" rows="8" id="custom_rules" name="custom_rules" placeholder='{"type":"ua_regex","value":"/Googlebot/i","action":"log","id":"audit_googlebot"}'><?php
					$rendered = [];

					foreach (($settings['custom_rules'] ?? []) as $rule)
					{
						$rendered[] = json_encode($rule, JSON_UNESCAPED_SLASHES);
					}

					echo htmlspecialchars(implode("\n", $rendered));
				?></textarea>
			</td>
		</tr>
		<tr class="hl-setting">
			<td class="label">
				<label for="body_scan_skip_fields"><strong><?php echo $engine->_t('BbBodyScanSkipFields');?></strong><br>
				<small><?php echo $engine->_t('BbBodyScanSkipFieldsInfo');?></small></label>
			</td>
			<td>
				<textarea cols="60" rows="4" id="body_scan_skip_fields" name="body_scan_skip_fields"><?php echo htmlspecialchars(implode("\n", $settings['body_scan_skip_fields'] ?? [])); ?></textarea>
			</td>
		</tr>

		<!-- REVERSE PROXY -->
		<tr><th colspan="2"><br><?php echo $engine->_t('BbReverseProxy');?></th></tr>
		<tr class="hl-setting"><td colspan="2"><div><?php echo Ut::perc_replace($engine->_t('BbReverseProxyInfo'), '<code><a href="https://en.wikipedia.org/wiki/X-Forwarded-For" rel="noreferrer">X-Forwarded-For</a></code>', '<code>X-Real-Ip</code> (nginx)', '<code>Cf-Connecting-Ip</code> (CloudFlare)');?><br></div></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="reverse_proxy"><?php echo $engine->_t('BbReverseProxyEnable');?></label></td>
			<td><input type="checkbox" id="reverse_proxy" name="reverse_proxy" value="1"<?php echo (!empty($settings['reverse_proxy']['enabled']) ? ' checked' : '');?>></td>
		</tr>
		<tr class="lined"><td colspan="2"></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="reverse_proxy_header"><?php echo $engine->_t('BbReverseProxyHeader');?></label></td>
			<td><input type="text" size="32" id="reverse_proxy_header" name="reverse_proxy_header" value="<?php echo htmlspecialchars($settings['reverse_proxy']['header'] ?? 'X-Forwarded-For'); ?>"></td>
		</tr>
		<tr class="lined"><td colspan="2"></td></tr>
		<tr class="hl-setting">
			<td class="label"><label for="reverse_proxy_addresses"><?php echo $engine->_t('BbReverseProxyAddresses');?></label></td>
			<td><textarea cols="30" rows="6" id="reverse_proxy_addresses" name="reverse_proxy_addresses"><?php echo htmlspecialchars(implode("\n", $settings['reverse_proxy']['addresses'] ?? [])); ?></textarea></td>
		</tr>
	</table>
	<br>
	<div class="center"><button type="submit" class="button" name="submit"><?php echo $engine->_t('UpdateButton');?></button></div>
<?php
	echo $engine->form_close();
?>
	</div>
<?php
	}

	// ============================================================
	// DISPATCH — runs once on every admin page load
	// ============================================================

	if ($action == 'bb2_options')
	{
		// Save BB settings to bb_config.php
		$save = bb2_save_settings($engine);

		if ($save['success'])
		{
			$engine->log(1, '!!' . $engine->_t('BbSettingsUpdated') . '!!');
			$engine->set_message($engine->_t('BbSettingsUpdated'));
			$engine->http->redirect($engine->href());
		}
		else
		{
			// Re-render form with submitted values + error message
			$engine->log(3, '!!' . $engine->_t('BbSettingsSaveFailed') . ': ' . $save['error'] . '!!');
			$engine->http->redirect($engine->href('', '', [
				'setting'       => 'bb2_options',
				'bb_save_error' => base64_encode($save['error']),
			]));
		}
	}

	if ($action == 'bb2_options_enable')
	{
		// Toggled from the disabled-state form (when ext_bad_behaviour = 0)
		$config['ext_bad_behaviour'] = (int)($_POST['ext_bad_behaviour'] ?? 0);
		$engine->db->_set($config);
		$engine->log(1, '!!' . $engine->_t('BbSettingsUpdated') . '!!');
		$engine->set_message($engine->_t('BbSettingsUpdated'));
		$engine->http->redirect($engine->href());
	}

	if ($action == 'purge_badbehaviour')
	{
		$sql = 'TRUNCATE ' . $engine->prefix . 'bad_behaviour';
		$engine->db->sql_query($sql);
		$engine->db->invalidate_sql_cache();
	}

	#######################################################################################################


	?>
	<h1><?php echo $engine->_t($module)['title']; ?></h1>
	<br>
	<?php echo Ut::perc_replace($engine->_t('BbInfo'), '<a href="https://github.com/Bad-Behaviour/badbehaviour" rel="noreferrer">Bad Behaviour</a>');?>
	<br><br>
	<?php
	$mode_selector	= 'setting';
	$mode			= $_GET[$mode_selector] ?? '';

	$tabs	= [
		''					=> 'BbSummary',
		'bb2_manage'		=> 'BbLog',
		'bb2_options'		=> 'BbSettings',
		'bb2_whitelist'		=> 'BbWhitelist',
	];

	if (!array_key_exists($mode, $tabs))
	{
		$mode = '';
	}

	echo '<h2>' . $engine->_t($tabs[$mode]) . '</h2>';
	echo '<p>' . $engine->tab_menu($tabs, $mode, '', [], $mode_selector) . '</p><br>';

	if (!empty($engine->db->ext_bad_behaviour))
	{
		if (isset($_GET['setting']) && $_GET['setting'] == 'bb2_options')
		{
			bb2_options($engine);
		}
		else if (isset($_GET['setting']) && $_GET['setting'] == 'bb2_whitelist')
		{
			bb2_whitelist($engine);
		}
		else if (isset($_GET['setting']) && $_GET['setting'] == 'bb2_manage')
		{
			bb2_manage($engine);
		}
		else
		{
			bb2_summary($engine);
		}
	}
	else
	{
		// Disabled state — show only the master enable switch
		echo $engine->form_open('bb2_options', ['form_more' => 'setting=bb2_options_enable']);
	?>
		<br>
		<table class="formation">
			<colgroup>
				<col span="1">
				<col span="1" style="width:50%;">
			</colgroup>
			<tbody>
				<tr class="hl-setting">
					<th scope="row" class="label">
						<strong><?php echo $engine->_t('BbEnable');?></strong><br>
						<small><?php echo Ut::perc_replace($engine->_t('BbEnableInfo'), '<code>bb_config.php</code>');?></small>
					</th>
					<td>
						<input type="radio" id="enable_bad-behaviour_on" name="ext_bad_behaviour" value="1" <?php echo ($engine->db->ext_bad_behaviour ? ' checked' : '');?>>
						<label for="enable_bad-behaviour_on"><?php echo $engine->_t('On');?></label>
						<input type="radio" id="enable_bad-behaviour_off" name="ext_bad_behaviour" value="0" <?php echo (!$engine->db->ext_bad_behaviour ? ' checked' : '');?>>
						<label for="enable_bad-behaviour_off"><?php echo $engine->_t('Off');?></label>
					</td>
				</tr>
			</tbody>
		</table>
		<br>
		<div class="center"><button type="submit" class="button" name="submit"><?php echo $engine->_t('UpdateButton');?></button></div>
	<?php
		echo $engine->form_close();
	}
}