lang = {
	// default.js
	ReallySave: 'Varmasti tallennettu?',
	ModifiedHint: 'Kenttä on muuttunut, älä unohda tallentaa muutoksia.',
	NotSavedWarning: 'Et tallentanut muutoksia. Oletko varma, että haluat lähteä?',
	SessionExpiredEditor: 'Istuntosi on vanhentunut!\nOlet kirjautunut pois käytöstä pitkään ollessasi.\n1. Tallenna lomakkeen muokkaukset tekstitiedostoon estääksesi menetyksen.\n2. Päivitä sivu.\n3. Kirjaudu uudelleen ja lähetä uudelleen.',
	// wikiedit.js
	HelpAbout: 'Ohjeet & Tietoja',
	HelpFormatting: 'Ohje',
	HelpFormattingTip: 'Ohjeet Wiki-muotoiluissa',
	HelpFormattingPage: 'Doc/English/Formatting',
	Heading1: 'Otsake 1',
	Heading2: 'Otsake 2',
	Heading3: 'Otsake 3',
	Heading4: 'Otsake 4',
	Heading5: 'Otsake 5',
	Heading6: 'Otsake 6',
	Bold: 'Bold',
	Italic: 'Italic',
	Underline: 'Alleviivaa',
	Strikethrough: 'Yliviivaus',
	Small: 'Pieni',
	Code: 'Sisäinen koodi',
	Superscript: 'Yläindeksi',
	Subscript: 'Alaindeksi',
	List: 'Lista',
	NumberedList: 'Numeroitu luettelo',
	Left: 'Vasen',
	Center: 'Keskitetty',
	Right: 'Oikea',
	Justify: 'Tasaa',
	Outdent: 'Lähtevä',
	Indent: 'Sisennys',
	CodeWrapper: 'Wrapper Koodi',
	HTML: 'HTML',
	Action: 'Toiminto',
	Line: 'Viiva',
	Signature: 'Allekirjoitus',
	Quote: 'Tarjous',
	MarkedText: 'Merkitty teksti',
	HighlightText: 'Korosta teksti',
	Shade: 'Varjosta',
	Footnote: 'Alaviite',
	Hyperlink: 'Hyperlinkki',
	InsertTable: 'Lisää taulu',
	Link: 'Linkki',
	TextForLinking: 'Linkitystä koskeva teksti',
	HelpAboutTip: ' Pikanäppäimet:\n' + ' Ctrl+B - Lihavoitu\n' + ' Ctrl+I - Italic\n' + ' Ctrl+U - Alleviivaus\n' + ' Ctrl+Shift+S - Yliviivaus\n' + ' Ctrl+Shift+1 .. 4 - Otsake 1..4\n' + ' Alt+I tai Ctrl+T - Sisennys\n' + ' Alt+U tai Ctrl+Shift+T - sisennys\n' + ' Ctrl+J - MarkUp (!!)\n' + ' Ctrl+H - MarkUp (??)\n' + ' Alt+L - Linkki\n' + ' Ctrl+L - Linkki kuvauksella\n' + ' Ctrl+Shift+L - Järjestämätön Luettelo\n' + ' Ctrl+Shift+N - Järjestetty Luettelo\n' + ' Ctrl+Shift+O - Järjestetty Luettelo\n' + ' Ctrl+= - Pieni teksti\n' + ' Ctrl+Shift+Minus - Vaakaviiva\n' + ' \n'
};