lang = {
	// default.js
	ReallySave: 'Virkelig lagre?',
	ModifiedHint: 'Feltet er endret, ikke glem å lagre endringene.',
	NotSavedWarning: 'Du lagret ikke endringene. Er du sikker på at du vil forlate?',
	SessionExpiredEditor: 'Økten er utløpt!\nDu har blitt logget av på grunn av lang inaktivitet.\n1. Lagre skjemaet redigeres til tekstfil for å forhindre tap.\n2. Oppdater siden.\n3. Logg inn igjen og sende inn på nytt.',
	// wikiedit.js
	HelpAbout: 'Hjelp og om',
	HelpFormatting: 'Hjelp',
	HelpFormattingTip: 'Hjelp til med Wiki-formatering',
	HelpFormattingPage: 'Doc/English/Formatting',
	Heading1: 'Overskrift 1',
	Heading2: 'Overskrift 2',
	Heading3: 'Overskrift 3',
	Heading4: 'Overskrift 4',
	Heading5: 'Overskrift 5',
	Heading6: 'Overskrift 6',
	Bold: 'Bold',
	Italic: 'Italic',
	Underline: 'Understreking',
	Strikethrough: 'Gjennomstreking',
	Small: 'Liten',
	Code: 'Inline kode',
	Superscript: 'Hevet',
	Subscript: 'Senket',
	List: 'Liste',
	NumberedList: 'Nummerert liste',
	Left: 'Venstre',
	Center: 'Midtstilt',
	Right: 'Høyre',
	Justify: 'Juster',
	Outdent: 'Utendørs',
	Indent: 'Innrykk',
	CodeWrapper: 'Code Wrapper',
	HTML: 'HTML',
	Action: 'Handling',
	Line: 'Linje',
	Signature: 'Signatur',
	Quote: 'Sitat',
	MarkedText: 'Merket tekst',
	HighlightText: 'Uthev tekst',
	Shade: 'Skygge',
	Footnote: 'Fotnote',
	Hyperlink: 'Hyperkobling',
	InsertTable: 'Sett inn tabell',
	Link: 'Lenke',
	TextForLinking: 'Tekst for å koble til',
	HelpAboutTip: ' Snarveier:\n' + ' Ctrl+B - fet\n' + ' Ctrl+I - Italic\n' + ' Ctrl+U - Understrek\n' + ' Ctrl+Shift+S - Gjennomstreking\n' + ' Ctrl+Shift+1 ... 4 - Overskrift 1..4\n' + ' Alt+I eller Ctrl+T - Indent\n' + ' Alt+U eller Ctrl+Shift+T - Ikke innrykk\n' + ' Ctrl+J - MarkUp (!!)\n' + ' Ctrl+H - MarkUp (??)\n' + ' Alt+L - Link\n' + ' Ctrl+L - Lenke med beskrivelse\n' + ' Ctrl+Shift+L - Usortert liste\n' + ' Ctrl+Shift+N - Bestilt liste\n' + ' Ctrl+Shift+O - Bestilt liste\n' + ' Ctrl+= - Liten tekst\n' + ' Ctrl+Shift+Minus - Liggende linje\n' + ' \n'
};